### ISSUE TITLE
Launch Collision Avoidance Failed

### ISSUE THREAD

**Issue by peterhpchen** [rticommunity/rticonnextdds-usecases-automotive#6]
## Environment

* OS : Windows 10
* VS : Visual Studio 2017

## Reproducing

1. Open `ExampleCode\win32\Automotive-vs2017.sln` By Visual Studio 2017
1. Build (**Release** config and **Win32** platform)
1. Execute `scripts\launch.bat`

## Expected Result

All run fine.

## Real Result

![image](https://user-images.githubusercontent.com/6873700/57830955-48dae800-77e6-11e9-86dd-ed582ce6289b.png)

It can not find `collisionAvoidance.exe`

## Fix

* Modify `launch.bat:40` to `start %obj_dir%\collision_avoidance.exe`

https://github.com/rticommunity/rticonnextdds-usecases-automotive/blob/5fa0332f3d69d8e846f09a8cad11eca3ad940917/ExampleCode/scripts/launch.bat#L40

## Conclusion

It should be a simple naming error.

Thank you.

**Comment by neil-rti** [comment]
Hello Peter -- thank you for the detailed issue report!!
This issue has been fixed [here](https://github.com/neil-rti/rticonnextdds-usecases-automotive) and will be pulled into this repo shortly.   This is actually an output file naming inconsistency in 3 of the vcxproj files; update those files, the launch.bat file can be left as-is.
Thanks again for bringing this issue to attention  :)

**Comment by fgaranda** [comment]
The fixed has already been merged into the master branch. We can close this issue.
